name: hash_identifier
description: Library for identifying hashing algorithm ported from python's hashid library.
version: 2.0.0
homepage: https://github.com/aquilax/hash-identifier-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
